spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST:192.168.56.101}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}

management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: info